#!/bin/bash

# Supabase Edge Function Deployment & Configuration Guide
# Run these commands manually in Supabase Dashboard

echo "================================================"
echo "SUPABASE EDGE FUNCTION SETUP"
echo "================================================"
echo ""
echo "1. Go to Supabase Dashboard: https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Navigate to: Edge Functions → Secrets"
echo ""
echo "4. Add these secrets:"
echo ""
echo "   GOOGLE_API_KEY = AIzaSyAb8RN6INGlFVpWibAob5Ur_GnYqECngf4suGF6WPqu1yOjAu_w"
echo ""
echo "   GA_PROPERTY_ID = properties/YOUR_PROPERTY_ID"
echo "   (Find this in Google Analytics → Admin → Property Settings)"
echo ""
echo "================================================"
echo "DEPLOYING EDGE FUNCTION"
echo "================================================"
echo ""
echo "Option 1: Deploy via Supabase Dashboard"
echo "   1. Go to: Edge Functions → Deploy new function"
echo "   2. Upload: supabase/functions/google-analytics/index.ts"
echo "   3. Name: google-analytics"
echo "   4. Click Deploy"
echo ""
echo "Option 2: Deploy via CLI (if Supabase CLI installed)"
echo "   Run: supabase functions deploy google-analytics"
echo ""
echo "================================================"
echo "DATABASE SETUP"
echo "================================================"
echo ""
echo "Run this SQL in Supabase SQL Editor:"
echo ""
cat supabase/add-seo-metrics-columns.sql
echo ""
echo "================================================"
echo "TESTING"
echo "================================================"
echo ""
echo "After deployment, test the function:"
echo ""
echo "curl -X POST https://YOUR_PROJECT_REF.supabase.co/functions/v1/google-analytics \\"
echo "  -H 'Authorization: Bearer YOUR_ANON_KEY' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"action\": \"fetch_analytics\"}'"
echo ""
echo "================================================"
